---
- hosts: local
  connection: local
  gather_facts: False

  vars_files:
    - aws_keys.yml

  tasks:
  - name: Provision Backend instance
    ec2:
       key_name:                            #pem file name
       instance_type: t2.micro              #instance type
       image: ami-07ebfd5b3428b6f4d         #ubuntu18 image
       wait: true
       vpc_subnet_id:                       #vpc id
       group_id:                            #security group id
       exact_count: 1
       count_tag:
          Name: backend
       instance_tags:
          Name: backend
       assign_public_ip: yes
       region:                            #region
    vars:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_access: "{{ aws_secret_key }}"
    register: ec2


  - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
    local_action: lineinfile
                  dest="./hosts"
                  insertafter='\[backendservers]' line={{ item.public_ip }}
    with_items: "{{ ec2.instances }}"


  - name: Waiting for the instance to come
    local_action: wait_for
                  host={{ item.public_ip }}
                  state=started
                  port=22
    with_items: "{{ ec2.instances }}"

- hosts: backendservers
  name: Run role for Backend Servers
  user: ubuntu
  become: yes
  gather_facts: true
  vars:
    - warfile: "companyNews.war"
    - war_deploy_path: "/var/lib/tomcat8/webapps"
  roles:
    - deploy-nginx
    - deploy-backend
